export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_ATTEMPT = 'AUTH_ATTEMPT';
export const PROFILE_FOUND = 'PROFILE_FOUND';
export const PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND';
